var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__09wms4k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_06htc1..js")
R.c("server/chunks/ssr/[root-of-the-server]__04~pqog._.js")
R.c("server/chunks/ssr/node_modules_10n6ife._.js")
R.c("server/chunks/ssr/node_modules_@opentelemetry_api_build_esm_00a_hhy._.js")
R.c("server/chunks/ssr/_07imft5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_profile_page_actions_0r.ifsl.js")
R.m(70804)
module.exports=R.m(70804).exports
